name: mobile_erp
description: "CMS VINA MOBILE APP"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  english_words: ^4.0.0
  font_awesome_flutter: ^10.2.1
  http: ^1.1.0
  shared_preferences: ^2.0.17
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.0+1
  cookie_jar: ^4.0.8
  get: ^4.6.5
  mobile_scanner : ^6.0.7
  qr_code_scanner: ^1.0.1
  audioplayers: ^6.4.0
  ota_update: ^7.0.1
  awesome_dialog: ^3.1.0
  moment_dart: ^4.0.1
  rive: ^0.13.20
  intl: ^0.20.2
  syncfusion_flutter_core: ^28.2.11
  syncfusion_flutter_gauges: ^28.2.11
  syncfusion_flutter_charts: ^28.2.11
  syncfusion_flutter_datagrid: ^28.2.11
  dropdown_model_list: ^2.1.0
  dropdown_search: ^6.0.2
  image_picker: ^1.1.2
  bottom_sheet: ^4.0.4
  marquee_text: ^2.5.0+1
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
  - assets/images/
  - assets/sound/
